//! `plaits/dsp/oscillator/harmonic_oscillator.h` -- a bank of `N` harmonics
//! generated by a Chebyshev-polynomial recurrence from a single sine.
//!
//! The C's `Render<first_harmonic_index>` picks, at compile time, whether the
//! recurrence starts at the fundamental (`== 1`, cheap path) or an arbitrary
//! harmonic (needs two real `Sine()` calls to seed it); `first_harmonic_index`
//! is a runtime parameter here instead.
//!
//! Ramping `N` amplitudes at once doesn't fit the borrow-based
//! [`ParameterInterpolator`] (it would need `N` disjoint `&mut` borrows into
//! one array); instead the start/increment/value bookkeeping is inlined over
//! plain `[f32; N]` locals, copied back to `self` once at the end -- the same
//! computation, just without needing `N` live borrows at once.

use super::sine_oscillator::{sine, sine_no_wrap};

#[derive(Debug, Clone, Copy)]
pub struct HarmonicOscillator<const N: usize> {
    phase: f32,
    frequency: f32,
    amplitude: [f32; N],
}

impl<const N: usize> Default for HarmonicOscillator<N> {
    fn default() -> Self {
        Self {
            phase: 0.0,
            frequency: 0.0,
            amplitude: [0.0; N],
        }
    }
}

impl<const N: usize> HarmonicOscillator<N> {
    pub fn init(&mut self) {
        *self = Self::default();
    }

    /// `Render<first_harmonic_index>(frequency, amplitudes, out, size)`.
    ///
    /// When `first_harmonic_index == 1` this overwrites `out`; otherwise (as
    /// in the C) it adds into it, so a caller layers several instances at
    /// different harmonic ranges into the same buffer.
    pub fn render(&mut self, first_harmonic_index: usize, mut frequency: f32, amplitudes: &[f32; N], out: &mut [f32]) {
        if frequency >= 0.5 {
            frequency = 0.5;
        }
        let size = out.len();

        let freq_start = self.frequency;
        let freq_increment = (frequency - freq_start) / size as f32;

        let mut amp_value = self.amplitude;
        let mut amp_increment = [0.0f32; N];
        for i in 0..N {
            let mut f = frequency * (first_harmonic_index + i) as f32;
            if f >= 0.5 {
                f = 0.5;
            }
            let target = amplitudes[i] * (1.0 - f * 2.0);
            amp_increment[i] = (target - self.amplitude[i]) / size as f32;
        }

        let mut phase = self.phase;
        let mut freq_value = freq_start;

        for o in out.iter_mut() {
            freq_value += freq_increment;
            phase += freq_value;
            if phase >= 1.0 {
                phase -= 1.0;
            }
            let two_x = 2.0 * sine_no_wrap(phase);
            let (mut previous, mut current) = if first_harmonic_index == 1 {
                (1.0, two_x * 0.5)
            } else {
                let k = first_harmonic_index as f32;
                (sine(phase * (k - 1.0) + 0.25), sine(phase * k))
            };

            let mut sum = 0.0f32;
            for i in 0..N {
                amp_value[i] += amp_increment[i];
                sum += amp_value[i] * current;
                let temp = current;
                current = two_x * current - previous;
                previous = temp;
            }
            if first_harmonic_index == 1 {
                *o = sum;
            } else {
                *o += sum;
            }
        }

        self.phase = phase;
        self.frequency = freq_value;
        self.amplitude = amp_value;
    }
}
