[package]
name = "mi-plaits"
description = "Rust port of Mutable Instruments Plaits (24-model macro oscillator)."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "plaits"
path = "src/lib.rs"

[dependencies]
mi-stmlib.workspace = true
libm = "0.2"
log = "0.4"
