//! `tides2/ramp_shaper.h` -- converts the phase counters generated by
//! [`crate::ramp_generator::RampGenerator`] into actual variable-slope
//! waveforms (or variants: EOA/EOR pulses, wavetable-shaped output).
//!
//! As in [`crate::ramp_generator`], the C's `RampMode`/`Range` template
//! parameters become plain runtime `match`es here.

use stmlib::polyblep::{
    next_blep_sample, next_integrated_blep_sample, this_blep_sample, this_integrated_blep_sample,
};

use crate::ramp_generator::{RampMode, Range};

pub struct RampShaper {
    next_sample: f32,
    previous_phase_shift: f32,
}

impl Default for RampShaper {
    fn default() -> Self {
        Self::new()
    }
}

impl RampShaper {
    pub fn new() -> Self {
        let mut s = RampShaper {
            next_sample: 0.0,
            previous_phase_shift: 0.0,
        };
        s.init();
        s
    }

    pub fn init(&mut self) {
        self.next_sample = 0.0;
        self.previous_phase_shift = 0.0;
    }

    pub fn band_limited_pulse(&mut self, phase: f32, frequency: f32, pw: f32) -> f32 {
        let pw = stmlib::constrain(pw, frequency * 2.0, 1.0 - 2.0 * frequency);

        let mut this_sample = self.next_sample;
        let mut next_sample = 0.0;

        let mut wrap_point = pw;
        if phase < pw * 0.5 {
            wrap_point = 0.0;
        } else if phase > 0.5 + pw * 0.5 {
            wrap_point = 1.0;
        }

        let d = phase - wrap_point;

        if d >= 0.0 && d < frequency {
            let t = d / frequency;
            let mut discontinuity = 1.0;
            if wrap_point != pw {
                discontinuity = -discontinuity;
            }
            if frequency < 0.0 {
                discontinuity = -discontinuity;
            }
            this_sample += this_blep_sample(t) * discontinuity;
            next_sample += next_blep_sample(t) * discontinuity;
        }

        next_sample += if phase < pw { 0.0 } else { 1.0 };
        self.next_sample = next_sample;

        this_sample
    }

    pub fn slope(&mut self, ramp_mode: RampMode, range: Range, phase: f32, phase_shift: f32, frequency: f32, pw: f32) -> f32 {
        match ramp_mode {
            RampMode::Ad => self.skewed_ramp(phase, 0.0, frequency, pw),
            RampMode::Ar => phase,
            RampMode::Looping => {
                if range == Range::Control {
                    self.skewed_ramp(phase, phase_shift, frequency, pw)
                } else {
                    self.band_limited_slope(phase, phase_shift, frequency, pw)
                }
            }
        }
    }

    pub fn eoa(&mut self, ramp_mode: RampMode, range: Range, phase: f32, frequency: f32, pw: f32) -> f32 {
        if ramp_mode == RampMode::Looping && range == Range::Audio {
            self.band_limited_pulse(phase, frequency, pw)
        } else if ramp_mode == RampMode::Ar {
            if phase >= 0.5 {
                1.0
            } else {
                0.0
            }
        } else if phase >= pw {
            1.0
        } else {
            0.0
        }
    }

    pub fn eor(&mut self, ramp_mode: RampMode, range: Range, phase: f32, frequency: f32, _pw: f32) -> f32 {
        if ramp_mode == RampMode::Looping {
            let pw = (0.5f32).min(96.0 * frequency);
            if range == Range::Audio {
                1.0 - self.band_limited_pulse(phase, frequency, pw)
            } else if phase < pw {
                1.0
            } else {
                0.0
            }
        } else if phase >= 1.0 {
            1.0
        } else {
            0.0
        }
    }

    fn band_limited_slope(&mut self, phase: f32, phase_shift: f32, frequency: f32, pw: f32) -> f32 {
        let mut phase = phase;
        let mut frequency = frequency;
        if phase_shift != 0.0 {
            phase += phase_shift;
            frequency += phase_shift - self.previous_phase_shift;
            self.previous_phase_shift = phase_shift;

            if phase >= 1.0 {
                phase -= 1.0;
            } else if phase < 0.0 {
                phase += 1.0;
            }
        }

        let pw = stmlib::constrain(pw, frequency.abs() * 2.0, 1.0 - 2.0 * frequency.abs());

        let mut this_sample = self.next_sample;
        let mut next_sample = 0.0;

        let mut wrap_point = pw;
        if phase < pw * 0.5 {
            wrap_point = 0.0;
        } else if phase > 0.5 + pw * 0.5 {
            wrap_point = 1.0;
        }

        let slope_up = 1.0 / pw;
        let slope_down = 1.0 / (1.0 - pw);
        let d = phase - wrap_point;

        if d >= 0.0 && d < frequency {
            let t = d / frequency;
            let mut discontinuity = -(slope_up + slope_down) * frequency;
            if wrap_point != pw {
                discontinuity = -discontinuity;
            }
            if frequency < 0.0 {
                discontinuity = -discontinuity;
            }
            this_sample += this_integrated_blep_sample(t) * discontinuity;
            next_sample += next_integrated_blep_sample(t) * discontinuity;
        }

        next_sample += if phase < pw {
            phase * slope_up
        } else {
            1.0 - (phase - pw) * slope_down
        };
        self.next_sample = next_sample;

        this_sample
    }

    fn skewed_ramp(&mut self, phase: f32, phase_shift: f32, frequency: f32, pw: f32) -> f32 {
        let mut phase = phase;
        let mut frequency = frequency;
        if phase_shift != 0.0 {
            phase += phase_shift;
            frequency += phase_shift - self.previous_phase_shift;
            self.previous_phase_shift = phase_shift;

            if phase >= 1.0 {
                phase -= 1.0;
            } else if phase < 0.0 {
                phase += 1.0;
            }
        }

        let pw = stmlib::constrain(pw, frequency.abs() * 2.0, 1.0 - 2.0 * frequency.abs());
        let slope_up = 0.5 / pw;
        let slope_down = 0.5 / (1.0 - pw);
        if phase < pw {
            phase * slope_up
        } else {
            (phase - pw) * slope_down + 0.5
        }
    }
}

pub struct RampWaveshaper {
    previous_input: f32,
    previous_output: f32,
    breakpoint: f32,
}

impl Default for RampWaveshaper {
    fn default() -> Self {
        Self::new()
    }
}

impl RampWaveshaper {
    pub fn new() -> Self {
        let mut s = RampWaveshaper {
            previous_input: 0.0,
            previous_output: 0.0,
            breakpoint: 0.0,
        };
        s.init();
        s
    }

    pub fn init(&mut self) {
        self.previous_input = 0.0;
        self.previous_output = 0.0;
        self.breakpoint = 0.0;
    }

    /// `shape` is a `[1025]`-x-row followed by a `[1025]`-y-row of the *next*
    /// wavetable row (`shape[1025..1027]`), i.e. a two-row window into
    /// `LUT_WAVETABLE` -- see `PolySlopeGenerator::RenderInternal`, which slices
    /// it as `&LUT_WAVETABLE[shape_integral * 1025..]`.
    pub fn shape(&mut self, ramp_mode: RampMode, input: f32, shape: &[i16], shape_fractional: f32) -> f32 {
        let ws_index = 1024.0 * input;
        let ws_index_integral = ws_index as i32;
        let ws_index_fractional = ws_index - ws_index_integral as f32;
        let ws_index_integral = (ws_index_integral & 1023) as usize;

        let x0 = shape[ws_index_integral] as f32 / 32768.0;
        let x1 = shape[ws_index_integral + 1] as f32 / 32768.0;
        let y0 = shape[ws_index_integral + 1025] as f32 / 32768.0;
        let y1 = shape[ws_index_integral + 1026] as f32 / 32768.0;
        let x = x0 + (x1 - x0) * ws_index_fractional;
        let y = y0 + (y1 - y0) * ws_index_fractional;
        let mut output = x + (y - x) * shape_fractional;

        if ramp_mode != RampMode::Ar {
            return output;
        }

        if (self.previous_input <= 0.5 && input > 0.5) || (self.previous_input > 0.5 && input < 0.5) {
            // Crossed the 0.5 midpoint in either direction.
            self.breakpoint = self.previous_output;
        } else if input == 1.0 {
            self.breakpoint = 1.0;
        } else if input == 0.5 {
            self.breakpoint = 0.0;
        }
        if input <= 0.5 {
            output = self.breakpoint + (1.0 - self.breakpoint) * output;
        } else {
            output *= self.breakpoint;
        }
        self.previous_input = input;
        self.previous_output = output;
        output
    }
}
