#!/usr/bin/env python3
"""Transpile a Mutable Instruments `resources.cc` / `resources.h` pair into a
single Rust source file of `pub static` arrays.

This is a deliberately small, format-specific parser -- the generated C is very
regular (it is itself emitted by `resources/resources.py`).  We only need to
handle:

  * `const <type> name[] = { ... };`            -> `pub static NAME: [T; N]`
  * `const <type>* name_table[] = { a, b, c };` -> `pub static NAME: [&[T]; N]`
  * `static const char foo[] = "bar";`          -> skipped (UI strings)

Usage:
    transpile_resources.py <module>/resources.cc <module>/resources.h out.rs
"""
import re
import sys

C_TYPE_TO_RUST = {
    "uint8_t": "u8",
    "int8_t": "i8",
    "uint16_t": "u16",
    "int16_t": "i16",
    "uint32_t": "u32",
    "int32_t": "i32",
    "float": "f32",
}

# Pointer tables: C name -> (rust name, element rust type)
POINTER_TABLES = {
    "lookup_table_table": "u16",
    "lookup_table_signed_table": "i16",
    "lookup_table_hr_table": "u32",
    "waveform_table": "i16",
    "waveshaper_table": "i16",
    "wt_table": "u8",
    "char_table": "u16",
    "string_table": None,  # skip
}


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def parse_arrays(cc_text: str):
    """Yield (c_name, c_type, is_pointer_table, values_or_names)."""
    cc_text = strip_comments(cc_text)
    # const uint16_t lut_foo[] = { ... };
    decl = re.compile(
        r"(?:static\s+)?const\s+(u?int(?:8|16|32)_t|float|char)\s*(\*?)\s*"
        r"([A-Za-z_][A-Za-z0-9_]*)\s*\[\]\s*=\s*\{(.*?)\}\s*;",
        re.S,
    )
    for m in decl.finditer(cc_text):
        c_type, star, name, body = m.groups()
        if c_type == "char":
            continue  # UI strings, not needed for DSP
        if star:
            names = [t.strip() for t in body.split(",") if t.strip()]
            yield name, c_type, True, names
        else:
            tokens = [t.strip() for t in body.split(",") if t.strip() != ""]
            yield name, c_type, False, tokens


def to_rust_literal(token: str, rust_type: str) -> str:
    token = token.strip()
    # Handle simple integer arithmetic that appears in a few tables (e.g. "12 * 128").
    if re.fullmatch(r"[-+0-9xXa-fA-F\s*()]+", token) and any(
        op in token for op in ("*", "+", "-", "(")
    ):
        try:
            value = eval(token, {"__builtins__": {}})  # noqa: S307 - trusted generated input
            token = str(value)
        except Exception:
            pass
    token = token.rstrip("Lu").rstrip("lL")
    if rust_type == "f32":
        if "." not in token and "e" not in token and "E" not in token:
            token += ".0"
        return token + "f32"
    return token


def main() -> int:
    cc_path, _h_path, out_path = sys.argv[1:4]
    with open(cc_path) as f:
        cc_text = f.read()

    module = re.search(r"namespace\s+([a-z_0-9]+)\s*\{", cc_text)
    module_name = module.group(1) if module else "resources"

    data_arrays = []
    pointer_tables = []
    for name, c_type, is_ptr, payload in parse_arrays(cc_text):
        if is_ptr:
            if name not in POINTER_TABLES or POINTER_TABLES[name] is None:
                continue
            pointer_tables.append((name, POINTER_TABLES[name], payload))
        else:
            data_arrays.append((name, C_TYPE_TO_RUST[c_type], payload))

    lines = [
        "// @generated by tools/transpile_resources.py -- do not edit by hand.",
        f"// Source: {cc_path}",
        "//",
        "// Lookup tables for the `{}` module, ported verbatim from the".format(module_name),
        "// numerically-generated C resource file.  Values are bit-identical to the",
        "// firmware build.",
        "#![allow(clippy::all)]",
        "#![cfg_attr(rustfmt, rustfmt::skip)]",
        "",
    ]

    for name, rust_type, tokens in data_arrays:
        rust_name = name.upper()
        literals = [to_rust_literal(t, rust_type) for t in tokens]
        lines.append(
            f"pub static {rust_name}: [{rust_type}; {len(literals)}] = ["
        )
        for i in range(0, len(literals), 12):
            lines.append("    " + ", ".join(literals[i : i + 12]) + ",")
        lines.append("];")
        lines.append("")

    for name, rust_type, members in pointer_tables:
        rust_name = name.upper()
        refs = ", ".join(f"&{m.upper()}" for m in members)
        lines.append(
            f"pub static {rust_name}: [&[{rust_type}]; {len(members)}] = [{refs}];"
        )
        lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(
        f"{out_path}: {len(data_arrays)} data arrays, "
        f"{len(pointer_tables)} pointer tables"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
